/**
 * Created by Administrator on 2017/4/19.
 */
export let tableDataTest = {
    content: [
        {
            billingOrg: '广州一智通',
            city: '广东省广州市海珠区',
            time: '2',
            middleCity: '佛山市',
            belongArea: '禅城区',
            phone: '13000000000',
            address: '天河区天平架5号空间',
            one: 1,
            two: 1,
            three: 1,
            four: 1,
            five: 1,
            six: 1,
            six2: 1,
            seven2: 1,
            four3: 1,
            five3: 1,
            six3: 1,
            seven3: 1,
            four4: 1,
            five4: 1,
            six4: 1,
            seven4: 1,
            four5: 1,
            five5: 1,
            six5: 1,
            seven5: 1
        },
        {
            billingOrg: '乐从营业网点',
            city: '广东省广州市海珠区',
            time: '2',
            middleCity: '佛山市',
            belongArea: '禅城区',
            phone: '13000000000',
            address: '天河区天平架5号空间',
            one: 1,
            two: 1,
            three: 1,
            four: 1,
            five: 1,
            six: 1,
            six2: 1,
            seven2: 1,
            four3: 1,
            five3: 1,
            six3: 1,
            seven3: 1,
            four4: 1,
            five4: 1,
            six4: 1,
            seven4: 1,
            four5: 1,
            five5: 1,
            six5: 1,
            seven5: 1
        },
        {
            billingOrg: '一智通',
            city: '广东省广州市海珠区',
            time: '2',
            middleCity: '佛山市',
            belongArea: '禅城区',
            phone: '13000000000',
            address: '天河区天平架5号空间',
            one: 1,
            two: 1,
            three: 1,
            four: 1,
            five: 1,
            six: 1,
            six2: 1,
            seven2: 1,
            four3: 1,
            five3: 1,
            six3: 1,
            seven3: 1,
            four4: 1,
            five4: 1,
            six4: 1,
            seven4: 1,
            four5: 1,
            five5: 1,
            six5: 1,
            seven5: 1
        }
    ],
    first: true,
    last: false,
    number: 0,
    numberOfElements: 4,
    size: 20,
    totalElements: 40,
    totalPages: 4
}